version: "3"

services:
  ubuntu-openvpn2socks5:
    build: .
    image: ubuntu-openvpn2socks5
    container_name: ubuntu-openvpn2socks5
    restart: unless-stopped
    devices:
      - /dev/net/tun
    volumes:
      - ./:/etc/openvpn/
    ports:
      - "127.0.0.1:8899:8899"
    cap_add:
      - NET_ADMIN
