version: "3.8"

services:
  vpn-proxy:
    build: .
    container_name: vpn-proxy
    network_mode: host  # Danted will be accessible from outside the Docker host machine.”
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - PROXY_USER=danted
      - PROXY_PASS=123secret
    volumes:
      - ./your-openvpn-config:/etc/openvpn
